INFO     WDM:logger.py:12 

INFO     WDM:logger.py:12 ====== WebDriver manager ======
INFO     WDM:logger.py:12 Current google-chrome version is 92.0.4515
INFO     WDM:logger.py:12 Get LATEST driver version for 92.0.4515
WARNING  urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fafb2a62340>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bcc8e975d1ec6dc74f722e3ab830ba38
WARNING  urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fafb2a5ab50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bcc8e975d1ec6dc74f722e3ab830ba38
WARNING  urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fafb2a5a0d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bcc8e975d1ec6dc74f722e3ab830ba38
INFO     WDM:logger.py:12 Driver [/home/runner/.wdm/drivers/chromedriver/linux64/92.0.4515.107/chromedriver] found in cache