INFO     WDM:logger.py:12 

INFO     WDM:logger.py:12 ====== WebDriver manager ======
WARNING  urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc93532ff10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/74ec26591606c794b09b1e474df39c05
WARNING  urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc93532fd00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/74ec26591606c794b09b1e474df39c05
WARNING  urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc9353836a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/74ec26591606c794b09b1e474df39c05
INFO     WDM:logger.py:12 Current google-chrome version is 92.0.4515
INFO     WDM:logger.py:12 Get LATEST driver version for 92.0.4515
INFO     WDM:logger.py:12 Driver [/home/runner/.wdm/drivers/chromedriver/linux64/92.0.4515.107/chromedriver] found in cache