INFO     WDM:logger.py:12 

INFO     WDM:logger.py:12 ====== WebDriver manager ======
INFO     WDM:logger.py:12 Current google-chrome version is 92.0.4515
INFO     WDM:logger.py:12 Get LATEST driver version for 92.0.4515
INFO     WDM:logger.py:12 Driver [/home/runner/.wdm/drivers/chromedriver/linux64/92.0.4515.107/chromedriver] found in cache
WARNING  urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f83554d8370>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/7826ff7bc89cd641897f2fbf9f8e9465
WARNING  urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8355041a60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/7826ff7bc89cd641897f2fbf9f8e9465
WARNING  urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f83550419a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/7826ff7bc89cd641897f2fbf9f8e9465